// AUTO-GENERATED by scripts/generate-mdx-map.mjs — do not edit manually
import type { ComponentType } from 'react'

export const mdxImports: Record<string, () => Promise<{
  default: ComponentType | null
  metadata?: { title?: string; group?: string; order?: number }
}>> = {
  'faq': () => import('../../../content/panel/faq.mdx'),
  'getting-started': () => import('../../../content/panel/getting-started.mdx'),
  'intro': () => import('../../../content/panel/intro.mdx'),
}
