// Generate mdx-map.ts from files in src/content/panel/*.mdx
// Run via: node scripts/generate-mdx-map.mjs
import fs from 'fs'
import path from 'path'

const ROOT = process.cwd()
const contentDir = path.join(ROOT, 'src', 'content', 'panel')
const outFile = path.join(ROOT, 'src', 'app', 'panel', 'components', 'mdx-map.ts')

function toId(filename) {
  return filename.replace(/\.(mdx|md)$/i, '')
}

function generate() {
  if (!fs.existsSync(contentDir)) {
    console.error('[generate-mdx-map] Missing directory:', contentDir)
    process.exit(0)
  }
  const files = fs
    .readdirSync(contentDir)
    .filter((f) => /\.(mdx|md)$/i.test(f))
  files.sort()

  const entries = files.map((f) => {
    const id = toId(f)
    const importPath = `../../../content/panel/${f}`
    return `  '${id}': () => import('${importPath}'),`
  })

  const content = `// AUTO-GENERATED by scripts/generate-mdx-map.mjs — do not edit manually\n` +
`import type { ComponentType } from 'react'\n\n` +
`export const mdxImports: Record<string, () => Promise<{\n` +
`  default: ComponentType | null\n` +
`  metadata?: { title?: string; group?: string; order?: number }\n` +
`}>> = {\n` +
entries.join('\n') + '\n' + `}\n`

  fs.writeFileSync(outFile, content, 'utf8')
  console.log(`[generate-mdx-map] Wrote ${outFile} with ${files.length} entries.`)
}

generate()


